{% set name = "certbot-apache" %}
{% set version = "1.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/certbot-apache-{{ version }}.tar.gz
  sha256: 03396fd227ebf0f92a529483437154d39de009fb1e5b709010cdf6eed65ef2f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - acme >={{ version }}
    - certbot >={{ version }}
    - python >=3.6
    - python-augeas
    - setuptools >=39.0.1

test:
  imports:
    - certbot_apache
    - certbot_apache._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: Apache plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
